// Code generated by sqlc. DO NOT EDIT.

package dao

import (
	"time"

	"github.com/google/uuid"
)

type Test struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
