// Code generated by sqlc. DO NOT EDIT.

package dao

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountChallenges(ctx context.Context) (int64, error)
	CountTestCases(ctx context.Context) (int64, error)
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (CreateChallengeRow, error)
	CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (CreateTestCaseRow, error)
	DeleteChallenge(ctx context.Context, id uuid.UUID) error
	DeleteTestCase(ctx context.Context, id uuid.UUID) error
	GetChallenge(ctx context.Context, id uuid.UUID) (GetChallengeRow, error)
	GetTestCase(ctx context.Context, id uuid.UUID) (GetTestCaseRow, error)
	ListChallenges(ctx context.Context, arg ListChallengesParams) ([]ListChallengesRow, error)
	ListExposedTestCases(ctx context.Context, arg ListExposedTestCasesParams) ([]ListExposedTestCasesRow, error)
	ListHiddenTestCases(ctx context.Context, arg ListHiddenTestCasesParams) ([]ListHiddenTestCasesRow, error)
	ListTestCases(ctx context.Context, arg ListTestCasesParams) ([]ListTestCasesRow, error)
	UpdateChallenge(ctx context.Context, arg UpdateChallengeParams) (UpdateChallengeRow, error)
	UpdateTestCase(ctx context.Context, arg UpdateTestCaseParams) (UpdateTestCaseRow, error)
}

var _ Querier = (*Queries)(nil)
