// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ChallengeController is an autogenerated mock type for the ChallengeController type
type ChallengeController struct {
	mock.Mock
}

// HandleDeleteChallenge provides a mock function with given fields: w, r
func (_m *ChallengeController) HandleDeleteChallenge(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// HandleGetChallenge provides a mock function with given fields: w, r
func (_m *ChallengeController) HandleGetChallenge(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// HandleGetChallenges provides a mock function with given fields: w, r
func (_m *ChallengeController) HandleGetChallenges(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// HandlePostChallenge provides a mock function with given fields: w, r
func (_m *ChallengeController) HandlePostChallenge(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// HandlePutChallenge provides a mock function with given fields: w, r
func (_m *ChallengeController) HandlePutChallenge(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
