// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/fikrirnurhidayat/codeotd/app/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ChallengeService is an autogenerated mock type for the ChallengeService type
type ChallengeService struct {
	mock.Mock
}

// CreateChallenge provides a mock function with given fields: _a0, _a1
func (_m *ChallengeService) CreateChallenge(_a0 context.Context, _a1 *entity.Challenge) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Challenge) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChallenge provides a mock function with given fields: _a0, _a1
func (_m *ChallengeService) DeleteChallenge(_a0 context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChallenge provides a mock function with given fields: _a0, _a1
func (_m *ChallengeService) GetChallenge(_a0 context.Context, _a1 uuid.UUID) (entity.Challenge, error) {
	ret := _m.Called(_a0, _a1)

	var r0 entity.Challenge
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Challenge); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(entity.Challenge)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListChallenges provides a mock function with given fields: _a0, _a1
func (_m *ChallengeService) ListChallenges(_a0 context.Context, _a1 *entity.Pagination) ([]entity.Challenge, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []entity.Challenge
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Pagination) []entity.Challenge); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Challenge)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.Pagination) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChallenge provides a mock function with given fields: _a0, _a1
func (_m *ChallengeService) UpdateChallenge(_a0 context.Context, _a1 *entity.Challenge) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Challenge) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
