// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/fikrirnurhidayat/codeotd/app/entity"
	mock "github.com/stretchr/testify/mock"
)

// PaginationService is an autogenerated mock type for the PaginationService type
type PaginationService struct {
	mock.Mock
}

// ConvertToOffset provides a mock function with given fields: _a0
func (_m *PaginationService) ConvertToOffset(_a0 *entity.Pagination) (entity.Offset, error) {
	ret := _m.Called(_a0)

	var r0 entity.Offset
	if rf, ok := ret.Get(0).(func(*entity.Pagination) entity.Offset); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(entity.Offset)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Pagination) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConvertToPagination provides a mock function with given fields: _a0, _a1, _a2
func (_m *PaginationService) ConvertToPagination(_a0 entity.Offset, _a1 int32, _a2 *entity.Pagination) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Offset, int32, *entity.Pagination) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
