// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/fikrirnurhidayat/codeotd/app/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TestCaseService is an autogenerated mock type for the TestCaseService type
type TestCaseService struct {
	mock.Mock
}

// CreateTestCase provides a mock function with given fields: _a0, _a1
func (_m *TestCaseService) CreateTestCase(_a0 context.Context, _a1 *entity.TestCase) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.TestCase) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTestCase provides a mock function with given fields: _a0, _a1
func (_m *TestCaseService) DeleteTestCase(_a0 context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTestCase provides a mock function with given fields: _a0, _a1
func (_m *TestCaseService) GetTestCase(_a0 context.Context, _a1 uuid.UUID) (entity.TestCase, error) {
	ret := _m.Called(_a0, _a1)

	var r0 entity.TestCase
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.TestCase); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(entity.TestCase)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTestCases provides a mock function with given fields: ctx, challengeId, pagination
func (_m *TestCaseService) ListTestCases(ctx context.Context, challengeId uuid.UUID, pagination *entity.Pagination) ([]entity.TestCase, error) {
	ret := _m.Called(ctx, challengeId, pagination)

	var r0 []entity.TestCase
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Pagination) []entity.TestCase); ok {
		r0 = rf(ctx, challengeId, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TestCase)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *entity.Pagination) error); ok {
		r1 = rf(ctx, challengeId, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTestCase provides a mock function with given fields: _a0, _a1, _a2
func (_m *TestCaseService) UpdateTestCase(_a0 context.Context, _a1 uuid.UUID, _a2 *entity.TestCase) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.TestCase) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
