// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/fikrirnurhidayat/codeotd/app/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ChallengeRepository is an autogenerated mock type for the ChallengeRepository type
type ChallengeRepository struct {
	mock.Mock
}

// CreateChallenge provides a mock function with given fields: _a0, _a1
func (_m *ChallengeRepository) CreateChallenge(_a0 context.Context, _a1 *entity.Challenge) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Challenge) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChallenge provides a mock function with given fields: _a0, _a1
func (_m *ChallengeRepository) DeleteChallenge(_a0 context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChallenge provides a mock function with given fields: _a0, _a1
func (_m *ChallengeRepository) GetChallenge(_a0 context.Context, _a1 uuid.UUID) (entity.Challenge, error) {
	ret := _m.Called(_a0, _a1)

	var r0 entity.Challenge
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Challenge); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(entity.Challenge)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListChallenges provides a mock function with given fields: _a0, _a1
func (_m *ChallengeRepository) ListChallenges(_a0 context.Context, _a1 entity.Offset) ([]entity.Challenge, int32, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []entity.Challenge
	if rf, ok := ret.Get(0).(func(context.Context, entity.Offset) []entity.Challenge); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Challenge)
		}
	}

	var r1 int32
	if rf, ok := ret.Get(1).(func(context.Context, entity.Offset) int32); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(int32)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, entity.Offset) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateChallenge provides a mock function with given fields: _a0, _a1, _a2
func (_m *ChallengeRepository) UpdateChallenge(_a0 context.Context, _a1 uuid.UUID, _a2 *entity.Challenge) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.Challenge) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
