name: Check
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
        check-latest: true
    - run: sudo apt-get install -qy software-properties-common 1> /dev/null
    - name: Prepare repository
      run: make setup 1> /dev/null
    - name: Test
      run: make test
